
POST http://localhost:3000/messages HTTP/1.1
content-type: application/json

{
    "content": "Hello Ohee"
}

### 

GET http://localhost:3000/messages HTTP/1.1

### 

GET http://localhost:3000/messages/633 HTTP/1.1
