
POST http://localhost:3000/messages-di HTTP/1.1
content-type: application/json

{
    "content": "Hello Oheee"
}

### 

GET http://localhost:3000/messages-di HTTP/1.1

### 

GET http://localhost:3000/messages-di/633 HTTP/1.1
